name: 'brobroli'

services:
  postgres:
    image: 'postgres:15-alpine3.19'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=brobroli
      - PGPASSWORD=root
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    container_name: postgres

  brobroli-back:
    image: delmas007/brobroli-back:0.0.1
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - my-network
    env_file:
      - .env
    container_name: brobroli-back

  brobroli-front:
    image: delmas007/brobroli-front:0.0.1
    ports:
      - '4200:4200'
    depends_on:
      - brobroli-back
    networks:
      - my-network
    container_name: brobroli-front

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
